name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: lint
        uses: docker://github/super-linter:v2.1.1
      - name: build
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - run: dotnet publish -c Release -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -r linux-x64
