name: CI

on: [push]

# on:
#   push:
#     branches:
#       - master

jobs:
  osx:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - run: dotnet publish -c Release -r osx-x64
