name: CI

on: push

jobs:
  build:
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   runtime: linux-x64
          - os: macos-latest
            runtime: osx-x64
          # - os: windows-lates
          #   rt: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: git clone
        uses: actions/checkout@master
      # - name: lint
      #   uses: docker://github/super-linter:v2.1.1
      - name: dotnet install
        uses: actions/setup-dotnet@v1
      #   if: matrix.os == 'ubuntu-latest'
      #   with:
      #     dotnet-version: 3.1.x
      # - name: build2
      #   run: brew install dotnet
      #   if: matrix.os == 'macos-latest'
      - name: dotnet publish
        run: dotnet publish -c Release -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -r ${{ matrix.runtime }}
      # - name: upload
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ matrix.rt }}
      #     path: bin/Release/netcoreapp3.1/${{ matrix.rt }}/publish/sql2csv
