name: main
on:
  push:
    branches:
    - master
    paths-ignore:
    - .github/CODEOWNERS
    - .github/dependabot.yml
    - .gitattributes
    - .gitignore
    - LICENSE
    - README.md
  pull_request:
    branches:
    - master
    paths-ignore:
    - .github/CODEOWNERS
    - .github/dependabot.yml
    - .gitattributes
    - .gitignore
    - LICENSE
    - README.md
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            goos: windows
            goarch: amd64
            output: sql2csv_windows_amd64.exe
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            output: sql2csv_linux_amd64
          - os: macos-latest
            goos: darwin
            goarch: amd64
            output: sql2csv_darwin_amd64
          - os: macos-latest
            goos: darwin
            arch: arm64
            output: sql2csv_darwin_arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: go build -o ${{ matrix.output }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}
