name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: windows
            arch: amd64
            output: sql2csv_windows_amd64.exe
          - os: linux
            arch: amd64
            output: sql2csv_linux_amd64.exe
          - os: darwin
            arch: amd64
            output: sql2csv_darwin_amd64.exe
          - os: darwin
            arch: arm64
            output: sql2csv_darwin_arm64.exe
    steps:
      - uses: actions/checkout@v2
      - name: go build -o ${{ matrix.output }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - run: ls -la
      # - name: upload
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ matrix.runtime }}
      #     path: bin/Release/netcoreapp3.1/${{ matrix.runtime }}/publish/${{ matrix.artifact }}
